// Shared helpers.

// Just the town/city name — drop any "(Province)" and anything after a comma
// (state, island, region) and any country. "Millbrook (ON)" → "Millbrook",
// "Hobart, Tasmania" → "Hobart", "Sukagawa (Fukushima)" → "Sukagawa".
export function cityShort(city) {
  if (!city) return "";
  return city.replace(/\s*\([^)]*\)/g, "").split(",")[0].trim();
}

// Grid views display the 800px thumbnail mirror of an image (generated by
// tools/make_thumbs.py); lightboxes keep the full-size original. Pair with
// thumbFallback so a missing thumb degrades gracefully to the original.
export function thumb(src) {
  return src && src.startsWith("public/") ? "public/thumbs/" + src.slice(7) : src;
}
export function thumbFallback(img, fullSrc) {
  img.addEventListener("error", () => {
    if (!img.src.endsWith(fullSrc)) img.src = fullSrc;
  }, { once: true });
}
